name: build
on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: generate-sources
        run: make
      - name: check-generated-sources
        run: |
          go mod tidy
          git diff --exit-code
      - name: compile-sources
        run: make build
