name: build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: generate-sources
        run: make
      - name: check-generated-sources
        run: |
          go mod tidy
          git diff --exit-code
      - name: compile-sources
        run: make build
